### PR TITLE
Add Composite Slices

### PR DESCRIPTION
**Pull request by levimykel**
This pull request adds functionality and tests for Composite Slices.

### CODE REVIEW

**Comment by arnaudlewis** [comment]
You could put label and sliceType in the interface Slice and define the getter for each one there.
Except for this, seems cool for me ;)

**Comment by srenault** [comment]
I'm on it!

**Comment by arnaudlewis** [comment]
I may have made a mistake. I think it's still java 7 so you won't be able to define the getter body there

**Comment by arnaudlewis** [comment]
@levimykel Could you resolve the conflicts please.

**Pull request merged**
