### PR TITLE
Add http proxy support

### PR DESCRIPTION
**Pull request by flegall**
- Add an optional proxy parameter to Api.get()
- Add a simple Proxy class containing proxy infos
- Modified HttpClient to handle proxy settings

### CODE REVIEW

**Comment by flegall** [comment]
I'm not so happy of those error messages in https://travis-ci.org/prismicio/java-kit/jobs/76643038
These come from the littleproxy library I'm using to test against. 
It seems harmless as it doesn't prevent the requests to pass the proxy.

**Comment by flegall** [comment]
Any plans on reviewing this PR ?

**Comment by erwan** [comment]
We're trying to keep the dependency list as small as possible, as it can creates conflicts if people use different versions in their project.

Could you configure the proxy on the JVM level, or the OS level?

**Comment by flegall** [comment]
The added dependency ("littleproxy") is only in "test" scope, it will not be included as a transitive dependency in production, it's only there for testing. 
The production code is still using java.net.URL (cf https://github.com/prismicio/java-kit/pull/37/files#diff-fc43e9ab68bde714df45aaa3dfeea6d1R29)

Yes as a workaround, we have configured the proxy to use for prismic urls at the JVM level using the java.net.ProxySelector class, but it's a bit cumbersome.

**Comment by erwan** [comment]
I see, that's nice. I'll take a closer look.

**Comment by srenault** [comment]
Your PR sounds interesting. I'll take a look ASAP. Sorry for the delay.

**Comment by ahouzi** [comment]
We don't need to create a proxy class since we have already java.net.proxy.
LittleProxy in 1.1.0 is stable and supports JAVA.
In HttpClient class we can just do the following work :
                       if (proxy != null) {
			connection = new URL(url).openConnection(proxy);
			} else {
			connection = new URL(url).openConnection();
			}

**Comment by srenault** [comment]
Okey!

**Pull request closed without merging**
